#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
spring:
  application:
    name: customer
#  config:
#    import: optional:configserver:http://localhost:8888
#application:
#  config:
#    cloth-url: http://localhost:8099/api/v1/cloth
