eureka:
  client:
    register-with-eureka: false
server:
  port: 8085
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: http://localhost:8090
          predicates:
            - path=/api/v1/students/**
